
spring:
#    datasource:
#        name: test
#        url: jdbc:mysql://127.0.0.1:3306/windy?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#        username: root
#        password: root
#        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver

##thymeleaf 静态资源配置
    thymeleaf:
       cache: false

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.winter.model

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
